name: Keep Supabase Alive

on:
  schedule:
    # Runs every 5 days at midnight UTC
    - cron: "0 0 */5 * *"
  workflow_dispatch: # allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Insert heartbeat row
        run: |
          curl -s "https://project/ydidkzndnksvghtdzmql.supabase.co/rest/v1/heartbeat" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"pinged_at": "'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"}'
